### ISSUE TITLE
Impossibile scaricare il file apk

### ISSUE THREAD

**Issue by GDKLESHER** [Spotifinity/app#1]
# Descrizione bug
Non posso scaricare l'ultima versione della mod

## Come riprodurre
Passi per trovare questo bug, parti dall'apertura dell'app.
- Clicca su "Esplora versioni"
- Clicca su "8.8.22.510"
- Clicca su "Inizia l'installazione" 2 volte

## Cosa dovrebbe succedere
Installare il file APK e non dare l'errore durante l'apertura di quel file

## Screenshots
Screenshots del bug allegati nella segnalazione

## Info telefono
 - Dispositivo: Huawei
 - Ver. Android: 10
 - Versione app: 4

**Comment by JustKleo** [comment]
Ci sto lavorando

**Comment by JustKleo** [comment]
Fatto, ora il link funziona
